=== madidia/TuxLetterGame/xml-resources/jaxb/ProfileBinding/profile.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           targetNamespace="http://myGame/tux"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:tux="http://myGame/tux"
           elementFormDefault="qualified">
    <xs:include schemaLocation="dico.xsd"/>
    <xs:element name="profile" type="tux:Profile"/>
    <xs:complexType name="Profile">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="avatar" type="xs:string"/>
            <xs:element name="birthday" type="xs:date"/>
            <xs:element name="games" type="tux:Games"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Games">
        <xs:sequence>
            <xs:element name="game" type="tux:Game" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Game">
        <xs:sequence>
            <xs:element name="time" type="xs:int" minOccurs="0" maxOccurs="1"/>
            <xs:element name="word" type="tux:Mot"/>
        </xs:sequence>
        <xs:attribute name="date" type="xs:date"/>
        <xs:attribute name="found" type="xs:string" use="optional"/>
    </xs:complexType>
</xs:schema>

=== madidia/TuxLetterGame/build/classes/xml/profile2.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<profile xmlns="http://myGame/tux" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://myGame/profile src/xml/profile.xsd">
    <name>Alban</name>
    <avatar>tux.jpeg</avatar>
    <birthday>2006-05-08</birthday>
    <games>
        <game date="2013-12-10" found="75%">
            <time>20</time>
            <word niveau="3">cle</word>
        </game>
        <game date="2010-12-11" found="30%">
            <time>30</time>
            <word niveau="2">manoir</word>
        </game>
        <game date="2015-11-12" found="30%">
            <time>35</time>
            <word niveau="1">vacances</word>
        </game>
    </games>
</profile>

=== madidia/TuxLetterGame/build/classes/xml/profile.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<?xml-stylesheet type="text/xsl" href="profile.xsl" ?>
<profile
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://myGame/tux'
    xsi:schemaLocation='http://myGame/tux profile.xsd' >
    <name>Alban</name>
    <avatar>tux.jpeg</avatar>
    <birthday>2006-05-08</birthday> 
    <games>
        <game date="2013-12-10" found="75%">           
            <word niveau="3">cle</word>
            <time>20</time>
        </game>  
        
        <game date="2010-12-11" found ="30%">
            <word niveau="2">manoir</word>
            <time>30</time>
        </game>
        
        <game date="2015-11-12" found ="30%">
            <word niveau="1">vacances</word>
            <time>35</time>
        </game>
        
    </games>
</profile>
